disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap

languageCode: en-us
baseURL: https://edvinas.dev

markup:
  highlight:
    codeFences: false

  goldmark:
    renderer:
      xHTML: true

params:
  description: technology, humans, explorations, web
  author: pinkfloppydisk
  name: pinkfloppydisk
  images:
    - icon.png
